services:
  backend:
#    image: quiz_image
    build: ./
    container_name: quiz_container
    working_dir: /quiz
    ports:
      - "8010:8000"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/quiz/src
      - ./commands:/quiz/commands/
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

#    ...
#  airflow:
#    ...
#  celery:
#    ...

volumes:
  pg_data: { }
  pgadmin: { }